=== HotariTobu/manaba-plus/hosts/_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "title": "Manaba Host",
    "description": "A host hosting manaba",

    "type": "object",
    "properties": {
        "name": {
            "description": "The name of school or university",
            "type": "string"
        },
        "source": {
            "description": "The URL of a site from which got manaba URL",
            "type": "string"
        },
        "tags": {
            "description": "SNS tags of the school or university",
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "manaba-url": {
            "description": "The prefix of manaba URL",
            "type": "string"
        },
        "bad-status": {
            "description": "URL of pages that should navigate the login page",
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "name",
        "source",
        "tags",

        "manaba-url",
        "bad-status"
    ]
}

=== HotariTobu/manaba-plus/hosts/gifu.json
{
    "$schema": "_schema.json",

    "name": "岐阜県立岐阜総合学園高等学校",
    "source": "https://school.gifu-net.ed.jp/wordpress/sogo-hs/%E3%80%8Cmanaba%E3%80%8D%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8/",
    "tags": [
        "#春から岐阜総合"
    ],

    "manaba-url": "https://gifu.manaba.jp/ct/",
    "bad-status": []
}

=== HotariTobu/manaba-plus/hosts/chuo-u.json
{
    "$schema": "_schema.json",

    "name": "中央大学",
    "source": "https://itc.r.chuo-u.ac.jp/com/manaba/",
    "tags": [
        "#春から中央",
        "#春から中大",
        "#春から中央大学"
    ],

    "manaba-url": "https://room.chuo-u.ac.jp/ct/",
    "bad-status": [
        "https://gakunin-idp.c.chuo-u.ac.jp/sso/timeout.cgi*",
        "https://gakunin-idp.c.chuo-u.ac.jp/saml/saml2/idp/SSOService.php*",
        "https://room.chuo-u.ac.jp/Shibboleth.sso/SLO/POST*",
        "https://room.chuo-u.ac.jp/Shibboleth.sso/SAML2/POST*"
    ]
}

=== HotariTobu/manaba-plus/2.x/hosts/osaka-shoin.json
{
    "name": "大阪樟蔭女子大学",
    "source": "https://manaba.osaka-shoin.ac.jp/ct/course_407236",
    "tags": [
        "#春からOSWU",
        "#春から樟蔭",
        "#春から大阪樟蔭",
        "#春から大阪樟蔭女子",
        "#春から大阪樟蔭女子大学"
    ],
    
    "manaba-url": "https://manaba.osaka-shoin.ac.jp/ct/",
    "bad-status": []
}
